use_frameworks!

platform :ios, '13.0'

target 'ZoomImageView_Example' do
  pod 'ZoomImageView', :path => '../'

  target 'ZoomImageView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
